Fix gcc arguments order
The command to build the example failed with gcc, because
-lwayland-client was passed before client.c:

    $ clang -o client client.c -lwayland-client
    $ gcc   -o client client.c -lwayland-client
    $ clang -o client -lwayland-client client.c
    $ gcc   -o client -lwayland-client client.c
    /usr/bin/ld: /tmp/ccgg4wcL.o: in function `main':
    client.c:(.text+0x15): undefined reference to `wl_display_connect'
    /usr/bin/ld: client.c:(.text+0x73): undefined reference to `wl_display_disconnect'
    collect2: error: ld returned 1 exit status